apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: blank-api
  description: "A simple Node.js API running on localhost:5000"
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/vikassn9982/node-api-backstage/blob/master/README.md
spec:
  type: openapi
  lifecycle: experimental
  owner: user  # ✅ This field is REQUIRED
  definition: |
    openapi: 3.0.0
    info:
      title: Blank API
      version: 1.0.0
    paths:
      /:
        get:
          summary: Root API test
          responses:
            '200':
              description: API is running
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      message:
                        type: string
      /api/hello:
        get:
          summary: Hello API
          responses:
            '200':
              description: A greeting message
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      message:
                        type: string
