apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: drcs-node-testapi
  description: Node.js API running on Kubernetes with KEDA
spec:
  type: openapi
  lifecycle: production
  owner: user
  definition: |
    openapi: 3.0.0
    info:
      title: My Node API
      version: 1.0.0
    paths:
      /users:
        get:
          summary: Get all users
          responses:
            '200':
              description: Success
      /upload:
        post:
          summary: Upload file to Azure
          responses:
            '201':
              description: File uploaded
